### ISSUE TITLE
Переезд на поддомен

### ISSUE THREAD

**Issue by yukisnowflake** [nmisec/gonepnep#1]
Отныне NeppedAPI работает на поддомене. Требуется переделать работу SDK для дальнейшей работы с API.
# Что требуется сделать?
Ранее чтобы обратиться к API, нужно было делать запрос на `neppedcord.top/api`. Теперь нужно делать запрос на `api.neppedcord.top` (без `/api`).

**Comment by ilyaoc** [comment]
👌
